export default function Head() {
  return (
    <>
      <title>Ethan-LN-portfolio-website</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://firebasestorage.googleapis.com/v0/b/portfolio-f533e.appspot.com/o/profileImgae%2Fbumblebee-round.png?alt=media&token=63e3362a-03fd-4cef-9911-db7d86a1ac56"/>
    </>
  )
}
